export enum MutationTypes {
  SET_ORGS = "SET_ORGS",
  SET_USERS = "SET_USERS",
  SET_REPOS = "SET_REPOS",
  SET_ORGS_LOADING = "SET_ORGS_LOADING",
  SET_USERS_LOADING = "SET_USERS_LOADING",
  SET_REPOS_LOADING = "SET_REPOS_LOADING",
}
